### ISSUE TITLE
DOM snapshot could not be created

### ISSUE THREAD

**Issue by ikOrbis** [kdzwinel/SnappySnippet#34]
Hello,

I am trying to inspect the element given in the image and its giving me an error: DOM snapshot could not be created. Could you please look into the issue and let me know when it will be fixed? I think your feature is amazing!

Cheers.

Original URL: http://www.templatemonster.com/demo/51109.html
![food element](https://cloud.githubusercontent.com/assets/12048979/8030822/e15ecce2-0dc1-11e5-8461-0940a2a0981b.PNG)
![snappysnippet error](https://cloud.githubusercontent.com/assets/12048979/8030823/e173b2ba-0dc1-11e5-9f5c-d1622f0eee44.PNG)

**Comment by kdzwinel** [comment]
You are trying to extract something from an iframe. This doesn't seem to be supported. Try selecting this element directly from http://livedemo00.template-help.com/wt_51109 .
