### ISSUE TITLE
How would we use this to get information from a website updating constantly? 

### ISSUE THREAD

**Issue by rycao18** [kdzwinel/SnappySnippet#39]
How would I use this if I wanted to get something happening live, for example, 

if you go to this website...
http://steamcommunity.com/market/listings/440/Mann%20Co.%20Supply%20Crate%20Key

and you scroll down to "Recent Activity", you see there are people posting things, and updates are occuring. How would I be able to continue to scrape the website each time it updates? 

Thank you in advance,
rycao18

**Comment by kdzwinel** [comment]
Hey, thanks for reaching out - constantly scraping websites is not SnappySnippet's goal, you can probably build something like that on the top of SnappySnippet code.
