### ISSUE TITLE
Bug when css content is empty double quote.

### ISSUE THREAD

**Issue by reggi** [kdzwinel/SnappySnippet#40]
When an element has `content` set to an empty string,

``` css
content: "";
```

It sets it to 

``` css
content: '""';
```

Which means something that should look like this:

![screen shot 2015-10-19 at 3 36 49 pm](https://cloud.githubusercontent.com/assets/296798/10589070/4aab1eda-7677-11e5-9f8f-64e522877cf2.png)

Looks like this:

![screen shot 2015-10-19 at 3 37 00 pm](https://cloud.githubusercontent.com/assets/296798/10589071/4aafb454-7677-11e5-900c-54b33ca140b3.png)

**Comment by kdzwinel** [comment]
Thanks for reporting!

Connected to: https://github.com/kdzwinel/SnappySnippet/issues/38

**Comment by kdzwinel** [comment]
Closing since it's a duplicate
