### ISSUE TITLE
Request to record Hover States and Responsiveness in Elements

### ISSUE THREAD

**Issue by sipraomer** [kdzwinel/SnappySnippet#43]
HI! I want to save snippets of elements with there hover states included. For now I can only save snippets for static elements. However, can't save the interactivity part of it.

For instance, in the following example

http://charlottetang.com/

I can only copy this
http://codepen.io/pen/

**Comment by kdzwinel** [comment]
Hey, thanks for reporting. This is a duplicate of #21. Add a 👍 there if you need this feature.
