### ISSUE TITLE
Can you give a link to download?

### ISSUE THREAD

**Issue by Invntrm** [kdzwinel/SnappySnippet#45]
chrome store does not working a bit
![2016-09-07_09-46-53](https://cloud.githubusercontent.com/assets/8476005/18302345/0e6535e2-74e0-11e6-8dd2-76195cf81df7.png)

**Comment by kdzwinel** [comment]
Have you managed to resolve that? It works just fine for me. What version of Chrome you are running, what OS? Can you check your system with virus scanner?

**Comment by Invntrm** [comment]
working now
