### ISSUE TITLE
Add option to use class names instead of ID's

### ISSUE THREAD

**Issue by aplicacionamedida** [kdzwinel/SnappySnippet#52]
With the prefix option , it's possible to avoid the conflict with any other class name. Using class names instead of ID's makes the snippet much more reusable.

This is my use case:
I want to convert the snippet to a template for my web application. If I am using class names instead of ID's , I can reuse the code and apply the template to several different items (for example, product search results, chat messages, a list of resources, a data table,...).

**Comment by kdzwinel** [comment]
The plan is to support original class'es - #25. This will probably also help with your use case.
