### ISSUE TITLE
Add 'Generate PNG image'

### ISSUE THREAD

**Issue by tmplinshi** [kdzwinel/SnappySnippet#56]
Hi, thanks very much for this extension.

My main use of this extension, is to creating png file from the extracted CSS/HTML. Currently I am using **phantomjs** to generate the png file, and using **ImageMagick** to autocrop the transparent edges. But this requires some copy paste, and it's a bit slow to run **phantomjs** and **ImageMagick**.

Before generating the image, I would like the HTML/CSS texareas to be editable. Because for example if I want to generate image from a button, I might want to remove the button text.

**Comment by kdzwinel** [comment]
You can use Chrome Devtools to make screenshots of nodes: https://twitter.com/ChromeDevTools/status/902662330240057344 . You can also use [puppeteer](https://github.com/GoogleChrome/puppeteer) instead (or chrome devtools protocol directly). I'm not planning on adding screenshot support to SnappySnippet.

**Comment by tmplinshi** [comment]
Thanks for the tips! This new feature in Chrome 62 is convenient enough. 😄

**Comment by kdzwinel** [comment]
Good to hear! :)
