### ISSUE TITLE
Send to Codepen and JSBin doesn't work

### ISSUE THREAD

**Issue by pookdeveloper** [kdzwinel/SnappySnippet#57]
In codepen it comes out empty, and the JSBin fails

**Comment by kdzwinel** [comment]
duplciate of #55 . Please make sure that the code you are exporting isn't too big, please check what happens when you are, and aren't, logged in to codepen/jsbin

**Comment by squalliram** [comment]
Send to CodePen and JSBin still doesn't work as of today. I've only gotten the JsFiddle option to work so far. Can you please check and make sure it works going forward. I love the tool and use it a lot but really would benefit it from working everytime.

Thanks.
