### ISSUE TITLE
Fourth output target: "open in new tab"

### ISSUE THREAD

**Issue by paul-hammant** [kdzwinel/SnappySnippet#58]
This so I can take a full page snapshot of the element I extracted via SnappySnippet. Specifically, a PNG of the page (formerly an element of another page) regardless of height.

**Comment by kdzwinel** [comment]
Not sure what you are exactly aiming for, but maybe you can the built-in DevTools feature: https://twitter.com/ChromeDevTools/status/902662330240057344

**Comment by paul-hammant** [comment]
ChromeCanary: Indeed it does - nice.

**Comment by kdzwinel** [comment]
Good to hear!
